In [17]:
import pandas as pd

In [18]:
df = pd.DataFrame({
    "Name": ["Aman","Saurav","Karan","Shubham","Abhishek",None,"Sameer"],
    "Age": [22,23,None,22,25,24,26],
    "Marks": [85,None, 88,90,56,72,None],
    "Subject": ["Math","Physics","Math","Chemistry","Math","Physics","Chemistry"]
})
df

       Name   Age  Marks    Subject
0      Aman  22.0   85.0       Math
1    Saurav  23.0    NaN    Physics
2     Karan   NaN   88.0       Math
3   Shubham  22.0   90.0  Chemistry
4  Abhishek  25.0   56.0       Math
5       NaN  24.0   72.0    Physics
6    Sameer  26.0    NaN  Chemistry

In [19]:
type(df)

pandas.DataFrame

In [20]:
df.describe()

             Age      Marks
count   6.000000   5.000000
mean   23.666667  78.200000
std     1.632993  14.254824
min    22.000000  56.000000
25%    22.250000  72.000000
50%    23.500000  85.000000
75%    24.750000  88.000000
max    26.000000  90.000000

In [21]:
df[["Name","Marks"]]

       Name  Marks
0      Aman   85.0
1    Saurav    NaN
2     Karan   88.0
3   Shubham   90.0
4  Abhishek   56.0
5       NaN   72.0
6    Sameer    NaN

In [22]:
df[df["Marks"]>80]

      Name   Age  Marks    Subject
0     Aman  22.0   85.0       Math
2    Karan   NaN   88.0       Math
3  Shubham  22.0   90.0  Chemistry

In [23]:
df[(df["Age"]>22)&(df["Marks"]>80)]

Empty DataFrame
Columns: [Name, Age, Marks, Subject]
Index: []

In [24]:
df["Subject"].value_counts

<bound method IndexOpsMixin.value_counts of 0         Math
1      Physics
2         Math
3    Chemistry
4         Math
5      Physics
6    Chemistry
Name: Subject, dtype: str>

In [25]:
desc =df.sort_values("Marks",ascending=False)
print(desc)

       Name   Age  Marks    Subject
3   Shubham  22.0   90.0  Chemistry
2     Karan   NaN   88.0       Math
0      Aman  22.0   85.0       Math
5       NaN  24.0   72.0    Physics
4  Abhishek  25.0   56.0       Math
1    Saurav  23.0    NaN    Physics
6    Sameer  26.0    NaN  Chemistry

In [26]:
desc.head(2)

      Name   Age  Marks    Subject
3  Shubham  22.0   90.0  Chemistry
2    Karan   NaN   88.0       Math

In [27]:
desc.tail(1)

     Name   Age  Marks    Subject
6  Sameer  26.0    NaN  Chemistry

In [28]:
df.isnull().sum()

Name       1
Age        1
Marks      2
Subject    0
dtype: int64

In [29]:
df[df["Marks"].isnull()]

     Name   Age  Marks    Subject
1  Saurav  23.0    NaN    Physics
6  Sameer  26.0    NaN  Chemistry

The Scenario: TechCorp HR Data

Context: You are an HR Data Analyst for "TechCorp". You have been provided with a DataFrame named df containing employee records.

The DataFrame df has the following columns:

Name: The employee’s name (contains some missing values).

Department: The department they work in (e.g., IT, Sales, HR).

Role: Their job title (e.g., Analyst, Manager, Developer).

Experience: Years of experience.

Salary: Annual salary in USD.

Score: Most recent performance review score (contains missing values for new hires).

Note: Assume the DataFrame df is already loaded into your Python environment.

In [35]:
df =pd.DataFrame ({
    "Name": ["Alice", "Bob", None, "David", "Eva", "Frank", "Grace", None, "Henry", "Ivy"],
    "Department": ["IT", "Sales", "HR", "IT", "Sales", "HR", "IT", "Sales", "HR", "IT"],
    "Role": ["Developer", "Manager", "Analyst", "Developer", "Executive",
             "Manager", "Analyst", "Executive", "Analyst", "Developer"],
    "Experience": [5, 8, 2, 6, 3, 10, 4, 1, 7, 9],
    "Salary": [75000, 90000, 50000, 80000, 60000, 95000, 70000, 45000, 85000, 100000],
    "Score": [4.5, 4.0, None, 4.2, None, 4.8, 3.9, None, 4.1, 4.7]
})
df


# Basic checks
print(df.shape)
print(df.dtypes)

# Missing values
print(df.isna().sum())

# Average salary per department
print(df.groupby("Department")["Salary"].mean())

# High performers
print(df[df["Score"] > 4.5])

# Employees with missing score
print(df[df["Score"].isna()])

(10, 6)
Name              str
Department        str
Role              str
Experience      int64
Salary          int64
Score         float64
dtype: object
Name          2
Department    0
Role          0
Experience    0
Salary        0
Score         3
dtype: int64
Department
HR       76666.666667
IT       81250.000000
Sales    65000.000000
Name: Salary, dtype: float64
    Name Department       Role  Experience  Salary  Score
5  Frank         HR    Manager          10   95000    4.8
9    Ivy         IT  Developer           9  100000    4.7
  Name Department       Role  Experience  Salary  Score
2  NaN         HR    Analyst           2   50000    NaN
4  Eva      Sales  Executive           3   60000    NaN
7  NaN      Sales  Executive           1   45000    NaN

Exercise Questions – Part 1

Write the exact Pandas code to answer the following questions.

Basic Averages

1. What is the average (mean) Salary for each Department?
2. What is the average (mean) Performance Score for each Role?

Counting and Sizing
3. How many actual, non-null Performance Score entries exist for each Department?
4. What is the total number of employee records (rows) in each Department, regardless of whether data is missing?

In [36]:
# 1️⃣ Average Salary for each Department
df.groupby("Department")["Salary"].mean()

# 2️⃣ Average Performance Score for each Role
df.groupby("Role")["Score"].mean()

# 3️⃣ Non-null Performance Score count per Department
df.groupby("Department")["Score"].count()

# 4️⃣ Total employee records per Department
df.groupby("Department").size()

Department
HR       3
IT       4
Sales    3
dtype: int64




Exercise Questions – Part 2

Multiple Aggregations

1. Generate a summary table for Salary based on Department that shows the mean, maximum, minimum, and count in a single line of code.
2. Generate the same summary table (mean, max, min, count) but analyze the Performance Score based on the Role.

Grouping by Multiple Columns

3. Find the average Salary grouped by both Department and Role.
4. Find the average Performance Score grouped by both Department and Experience level.

In [37]:
# 1️⃣ Salary summary by Department
df.groupby("Department")["Salary"].agg(["mean", "max", "min", "count"])

# 2️⃣ Performance Score summary by Role
df.groupby("Role")["Score"].agg(["mean", "max", "min", "count"])

# 3️⃣ Average Salary by Department and Role
df.groupby(["Department", "Role"])["Salary"].mean()

# 4️⃣ Average Performance Score by Department and Experience
df.groupby(["Department", "Experience"])["Score"].mean()

Department  Experience
HR          2             NaN
            7             4.1
            10            4.8
IT          4             3.9
            5             4.5
            6             4.2
            9             4.7
Sales       1             NaN
            3             NaN
            8             4.0
Name: Score, dtype: float64